// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAPBD.Data;

#nullable disable

namespace TestAPBD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestAPBD.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CourseId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Credits = 5,
                            ProfessorId = 1,
                            Semester = 1,
                            Title = "Database Systems"
                        },
                        new
                        {
                            CourseId = 2,
                            Credits = 4,
                            ProfessorId = 1,
                            Semester = 2,
                            Title = "Algorithms"
                        },
                        new
                        {
                            CourseId = 3,
                            Credits = 3,
                            ProfessorId = 2,
                            Semester = 2,
                            Title = "Calculus"
                        },
                        new
                        {
                            CourseId = 4,
                            Credits = 4,
                            ProfessorId = 2,
                            Semester = 3,
                            Title = "Linear Algebra"
                        },
                        new
                        {
                            CourseId = 5,
                            Credits = 5,
                            ProfessorId = 1,
                            Semester = 1,
                            Title = "Data Structures"
                        });
                });

            modelBuilder.Entity("TestAPBD.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("FacultyBuilding")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Budget = 1000000m,
                            FacultyBuilding = "A",
                            Name = "Computer Science"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Budget = 800000m,
                            FacultyBuilding = "B",
                            Name = "Mathematics"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Budget = 900000m,
                            FacultyBuilding = "C",
                            Name = "Physics"
                        });
                });

            modelBuilder.Entity("TestAPBD.Entities.Enrollment", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            StudentId = 1,
                            Grade = 4.5m,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseId = 1,
                            StudentId = 2,
                            Grade = 3.5m,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseId = 5,
                            StudentId = 1,
                            Grade = 4.8m,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseId = 5,
                            StudentId = 3,
                            Grade = 4.2m,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 2,
                            Grade = 3.0m,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("TestAPBD.Entities.Professor", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessorId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProfessorId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            ProfessorId = 1,
                            DepartmentId = 1,
                            Email = "alice.johnson@university.edu",
                            FirstName = "Alice",
                            LastName = "Johnson"
                        },
                        new
                        {
                            ProfessorId = 2,
                            DepartmentId = 2,
                            Email = "robert.smith@university.edu",
                            FirstName = "Robert",
                            LastName = "Smith"
                        },
                        new
                        {
                            ProfessorId = 3,
                            DepartmentId = 3,
                            Email = "maria.williams@university.edu",
                            FirstName = "Maria",
                            LastName = "Williams"
                        });
                });

            modelBuilder.Entity("TestAPBD.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EnrollmentYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "john.wick@student.edu",
                            EnrollmentYear = 2022,
                            FirstName = "John",
                            LastName = "Wick"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "anna.kowalska@student.edu",
                            EnrollmentYear = 2023,
                            FirstName = "Anna",
                            LastName = "Kowalska"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "peter.nowak@student.edu",
                            EnrollmentYear = 2021,
                            FirstName = "Peter",
                            LastName = "Nowak"
                        });
                });

            modelBuilder.Entity("TestAPBD.Entities.Course", b =>
                {
                    b.HasOne("TestAPBD.Entities.Professor", "Professor")
                        .WithMany("Courses")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("TestAPBD.Entities.Enrollment", b =>
                {
                    b.HasOne("TestAPBD.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestAPBD.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TestAPBD.Entities.Professor", b =>
                {
                    b.HasOne("TestAPBD.Entities.Department", "Department")
                        .WithMany("Professors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TestAPBD.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("TestAPBD.Entities.Department", b =>
                {
                    b.Navigation("Professors");
                });

            modelBuilder.Entity("TestAPBD.Entities.Professor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("TestAPBD.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
